export { default as approval } from "./approval.svelte";
export { default as detailapproval } from "./detailapproval.svelte";
export { default as detailproposal } from "./detailproposal.svelte";
export { default as home } from "./home.svelte";
export { default as pendaftaranproposal } from "./pendaftaranproposal.svelte";
export { default as ppmongoing } from "./ppmongoing.svelte";
export { default as profile } from "./profile.svelte";
export { default as proposalmanagement } from "./proposalmanagement.svelte";
export { default as select } from "./select.svelte";
